server:
  port: 9806
  servlet:
    context-path: /api/v1/

spring:
  timezone: UTC+08:00
  application:
    name: mars-k3i

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

redis:
  address: redis://${REDIS_HOSTNAME}:6379  # Redis server address with redis:// protocol
  password: ${REDIS_PASSWORD}
  database: 2                              # Default Redis database index

kafka:
  bootstrap-servers: ${KAFKA_SERVERS}
  security:
    protocol: SSL
    ssl:
      keystore-password: ${KAFKA_KEYSTORE_PASSWORD}
      key-password: ${KAFKA_KEY_PASSWORD}
      truststore-password: ${KAFKA_TRUSTSTORE_PASSWORD}
  consumer:
    enabled: true
    group-id: mars_k3i
    topics:
      - com.mars.k3.msg
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    auto-offset-reset: latest
  producer:
    enabled: true
    topics:
      - com.mars.k3.msg
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    retries: 0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"