server:
  port: 9807
  servlet:
    context-path: /api/v1/

spring:
  timezone: UTC+08:00
  application:
    name: mars-eventm

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

kafka:
  bootstrap-servers: ${KAFKA_SERVERS}
  security:
    protocol: SSL
    ssl:
      keystore-password: ${KAFKA_KEYSTORE_PASSWORD}
      key-password: ${KAFKA_KEY_PASSWORD}
      truststore-password: ${KAFKA_TRUSTSTORE_PASSWORD}
  consumer:
    enabled: true
    group-id: mars_eventm
    topic: com.mars.msg.k2,com.mars.msg.k3
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    auto-offset-reset: latest

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"