server:
  port: 9804
  servlet:
    context-path: /api/v1/

spring:
  timezone: UTC+08:00
  application:
    name: mars-k3mr

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mqtt:
  client:
    id: mqtt.k3mr
  broker:
    url: tcp://localhost:1883
  username: techstore
  password: m751eLp
    
interpreter-service:
  name: mars-k3i
  url: http://localhost:9806
  
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"