server:
  port: 9805
  servlet:
    context-path: /api/v1/

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      
spring:
  timezone: UTC+08:00
  application:
    name: mars-k3ms

eureka:
  client:
    service-url:
      defaultZone: http://mars-eureka:8761/eureka/

mqtt:
  client:
    id: mqtt.k3ms
  broker:
    url: tcp://chubb.mars-iot.cloud:51883
  username: techstore
  password: m751eLp
  
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"