server:
  port: 8086
  servlet:
    context-path: /api/v1/

spring:
  timezone: UTC+08:00
  application:
    name: mars-es
  mail:
  host: sgp1015.siteground.asia
  port: 465
  username: chubb-micc5000@mars-iot.cloud
  password: P37YC2T4qBtpuk9
  from: chubb-micc5000@mars-iot.cloud
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
        ssl:
          enable: true

jwt:
  auth:
    secret: UUtvOYvp9YHz/kQpTYTimW52hefnIW5eh49gnJHZqp4=
    expiration: 300000 # Access token lifespan (5 min)
    refreshExpiration: 86400000 # Refresh token lifespan (24 hours)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
redis:
  address: redis://127.0.0.1:6379     # Redis server address with redis:// protocol
  password: chubb@RE@20
  database: 2                       # Default Redis database index

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"