server:
  port: 9804
  servlet:
    context-path: /api/v1/

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      
spring:
  timezone: UTC+08:00
  application:
    name: mars-k3mr
  cloud:
    openfeign:
      compression:
        request:
          enabled: true
          mime-types: text/xml,application/xml,application/json
          min-request-size: 1024
        response:
          enabled: true
          
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

mqtt:
  client:
    id: mqtt.k3mr
  broker:
    url: tcp://${MQTT_HOST}:51883
  username: ${MQTT_USERNAME}
  password: ${MQTT_PASSWORD}
    
interpreter-service:
  name: ${INTERPRETER_NAME}
  url: ${INTERPRETER_HOSTNAME_URL}
  
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"