server:
  port: 9805
  servlet:
    context-path: /api/v1/
  compression:
    enabled: true
    mime-types: application/json, application/xml, text/html, text/plain
    min-response-size: 1024
    
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      
spring:
  timezone: UTC+08:00
  application:
    name: mars-k3ms
  cloud:
    openfeign:
      compression:
        request:
          enabled: true
          mime-types: text/xml,application/xml,application/json
          min-request-size: 1024
        response:
          enabled: true
          
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
    hostname: ${spring.cloud.client.ip-address}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

mqtt:
  client:
    id: mqtt.k3ms
  broker:
    url: tcp://${MQTT_HOST}:${MQTT_PORT}
  username: ${MQTT_USERNAME}
  password: ${MQTT_PASSWORD}
  
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"