server:
  port: 9806
  servlet:
    context-path: /api/v1/

spring:
  timezone: UTC+08:00
  application:
    name: mars-k3i

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
      
redis:
  address: redis://localhost:6379  # Redis server address with redis:// protocol
  password: chubb@RE@20
  database: 2                      # Default Redis database index
  
kafka:
  bootstrap-servers: localhost:9093
  security:
    protocol: SSL
    ssl:
      keystore-password: Techstore123
      key-password: Techstore123
      truststore-password: Techstore123
  producer:
    enabled: true
    topic: com.mars.msg.k3
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    retries: 0
    
device-service:
  name: mars-devm
  url: http://10.2.26.178:8085
  
template-service:
  name: mars-tempm
  url: http://10.2.26.178:9808

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"