server:
  port: 8182
  servlet:
    context-path: /api/v1/

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      
spring:
  timezone: UTC+08:00
  application:
    name: mars-citeh
  cloud:
    openfeign:
      compression:
        request:
          enabled: true
          mime-types: text/xml,application/xml,application/json
          min-request-size: 1024
        response:
          enabled: true
          
jwt:
  auth:
    secret: UUtvOYvp9YHz/kQpTYTimW52hefnIW5eh49gnJHZqp4=
    expiration: 300000 # Access token lifespan (5 min)
    refreshExpiration: 86400000 # Refresh token lifespan (24 hours)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
redis:
  address: redis://127.0.0.1:6379     # Redis server address with redis:// protocol
  password: chubb@RE@20
  database: 2                       # Default Redis database index

dev-control-service:
  name: mars-devc
  url: http://localhost:9812
  
user-service:
  name: mars-userm
  url: http://localhost:8083

devm-service:
  name: mars-devm
  url: http://localhost:8085
  
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"