server:
  port: 9804
  servlet:
    context-path: /api/v1/

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      
spring:
  timezone: UTC+08:00
  application:
    name: mars-k3mr
  cloud:
    openfeign:
      compression:
        request:
          enabled: true
          mime-types: text/xml,application/xml,application/json
          min-request-size: 1024
        response:
          enabled: true
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mqtt:
  client:
    id: mqtt.k3mr1
  broker:
    url: tcp://chubb.mars-iot.cloud:51883
  username: techstore
  password: m751eLp
    
interpreter-service:
  name: mars-k3i
  url: http://localhost:9806
  
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"