server:
  port: 9820
  servlet:
    context-path: /api/v1/

spring:
  timezone: UTC+08:00
  application:
    name: mars-smsr
        
camel:
  component:
    enabled: true
    smpp:
      configuration:
        url: "smpp://{{camel.component.smpp.configuration.system-id}}@{{camel.component.smpp.configuration.host}}:{{camel.component.smpp.configuration.port}}?password={{camel.component.smpp.configuration.password}}&enquireLinkTimer=3000&transactionTimer=5000&systemType=consumer"
        host: "smpp.seamway.com"
        port: "9000"
        password: "234567"
        system-id: "SMPP-21052"
        source-address: "7544"
        source-addr-ton: 0x05
        source-addr-npi: 0x01
        dest-addr-npi: 0x01
        dest-addr-ton: 0x01
    bean:
      scope: singleton

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"