server:
  port: 8761

spring:
  timezone: UTC+08:00
  application:
    name: mars-eureka

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  server:
    enable-self-preservation: false
    waitTimeInMsWhenSyncEmpty: 0
    renewalPercentThreshold: 0.33

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS