server:
  port: 9805
  servlet:
    context-path: /api/v1/

spring:
  timezone: UTC+08:00
  application:
    name: mars-k3ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mqtt:
  client:
    id: mqtt.k3ms
  broker:
    url: tcp://localhost:1883
  username: techstore
  password: m751eLp
  
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"