server:
  port: 8761

spring:
  timezone: UTC+08:00
  application:
    name: MARS-EUREKA

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    renewalPercentThreshold: 0.33

management:
  endpoints:
    web:
      exposure:
        include: "*"