server:
  port: 8080

spring:
  timezone: UTC+08:00
  application:
    name: mars-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
eureka:
  client:
    register-with-eureka: false
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      
jwt:
  auth:
    secret: UUtvOYvp9YHz/kQpTYTimW52hefnIW5eh49gnJHZqp4=
    expiration: 300000 # Access token lifespan (5 min)

management:
  endpoints:
    web:
      exposure:
        include: "*"