server:
  port: 9802
  servlet:
    context-path: /api/v1/
  compression:
    enabled: true
    mime-types: application/json, application/xml, text/html, text/plain
    min-response-size: 1024
    
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      
spring:
  timezone: UTC+08:00
  application:
    name: mars-k2eh
  cloud:
    openfeign:
      compression:
        request:
          enabled: true
          mime-types: text/xml,application/xml,application/json
          min-request-size: 1024
        response:
          enabled: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
    hostname: ${spring.cloud.client.ip-address}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      
redis:
  address: redis://${REDIS_HOSTNAME}:6379  # Redis server address with redis:// protocol
  password: chubb@RE@20
  database: 2                      # Default Redis database index

netty:
  port: 4440
  boss-count: 4
  worker-count: 20
  backlog: 2048
  keep-alive: true
  client-timeout: 20
    
interpreter-service:
  name: ${INTERPRETER_NAME}
  url: ${INTERPRETER_HOSTNAME_URL}
  
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"