server:
  port: 8999
  servlet:
    context-path: /api/v1/

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      
spring:
  timezone: UTC+08:00
  application:
    name: mars-citeh

jwt:
  auth:
    secret: UUtvOYvp9YHz/kQpTYTimW52hefnIW5eh49gnJHZqp4=
    expiration: 300000 # Access token lifespan (5 min)
    refreshExpiration: 86400000 # Refresh token lifespan (24 hours)

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    
redis:
  address: redis://${REDIS_HOSTNAME}:6379    # Redis server address with redis:// protocol
  password: chubb@RE@20
  database: 2                       # Default Redis database index

dev-control-service:
  name: ${DEVC_NAME}
  url: ${DEVC_HOSTNAME_URL}
  
user-service:
  name: ${USERM_NAME}
  url: ${USERM_HOSTNAME_URL}

devm-service:
  name: ${DEVM_NAME}
  url: ${DEVM_HOSTNAME_URL}
  
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"