server:
  port: 8080

spring:
  timezone: UTC+08:00
  application:
    name: mars-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':  # Applies to all paths
            allowedOrigins: 
                - "http://localhost:3000"
                - "http://10.2.26.178:3000"
                - "http://localhost:8100"
                - "http://tsm.mars-iot.cloud:54000"
                - "http://tsm.mars-iot.cloud:3000"
            allowedMethods: 
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
            allowedHeaders: 
                - "*"
            allowCredentials: true
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      
jwt:
  auth:
    secret: UUtvOYvp9YHz/kQpTYTimW52hefnIW5eh49gnJHZqp4=
    expiration: 300000 # Access token lifespan (5 min)

management:
  endpoints:
    web:
      exposure:
        include: "*"

socket-io:
  gateway: ${SOCKET_IO_GATEWAY}

soap:
  gateway: ${SOAP_GATEWAY}