server:
  port: 9804
  servlet:
    context-path: /api/v1/

spring:
  timezone: UTC+08:00
  application:
    name: mars-k3mr

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

mqtt:
  client:
    id: mqtt.k3mr
  broker:
    url: tcp://${MQTT_HOSTNAME}:51883
  username: techstore
  password: m751eLp
    
interpreter-service:
  name: ${K3I_NAME}
  url: ${K3I_HOSTNAME_URL}
  
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"