server:
  port: 9803
  servlet:
    context-path: /api/v1/

spring:
  timezone: UTC+08:00
  application:
    name: mars-k2i

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 

kafka:
  bootstrap-servers: 127.0.0.1:9093
  security:
    protocol: SSL
    ssl:
      keystore-password: Techstore123
      key-password: Techstore123
      truststore-password: Techstore123
  producer:
    enabled: true
    topic: com.mars.msg.k2
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    retries: 0
    
interpreter-service:
  name: mars-k2eh
  url: http://localhost:9802

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"