server:
  port: 8081
  servlet:
    context-path: /api/v1/
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
    
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
        
spring:
  timezone: UTC+08:00
  application:
    name: mars-aaa
  cloud:
    openfeign:
      compression:
        request:
          enabled: true
          mime-types: text/xml,application/xml,application/json
          min-request-size: 1024
        response:
          enabled: true
          
jwt:
  auth:
    secret: UUtvOYvp9YHz/kQpTYTimW52hefnIW5eh49gnJHZqp4=
    expiration: 86400000 # Access token lifespan (10 min)
    refreshExpiration: 86400000 # Refresh token lifespan (24 hours)

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
      
redis:
  address: redis://127.0.0.1:6379     # Redis server address with redis:// protocol
  password: chubb@RE@20
  database: 2                       # Default Redis database index

mail:
  host: sgp1015.siteground.asia
  port: 465
  username: chubb-micc5000@mars-iot.cloud
  password: P37YC2T4qBtpuk9
  from: chubb-micc5000@mars-iot.cloud
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
        ssl:
          enable: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    
user-service:
  name: mars-userm
  url: http://localhost:8083