server:
  port: 9807
  servlet:
    context-path: /api/v1/

spring:
  timezone: UTC+08:00
  application:
    name: mars-eventm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 

kafka:
  bootstrap-servers: 127.0.0.1:9093
  security:
    protocol: SSL
    ssl:
      keystore-password: Techstore123
      key-password: Techstore123
      truststore-password: Techstore123
  consumer:
    enabled: true
    group-id: mars_eventm
    topic: com.mars.msg.k2,com.mars.msg.k3
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    auto-offset-reset: latest

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"