server:
  port: 9805
  servlet:
    context-path: /api/v1/
  compression:
    enabled: true
    mime-types: application/json, application/xml, text/html, text/plain
    min-response-size: 1024
    
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      
spring:
  timezone: UTC+08:00
  application:
    name: mars-k3ms
  cloud:
    openfeign:
      compression:
        request:
          enabled: true
          mime-types: text/xml,application/xml,application/json
          min-request-size: 1024
        response:
          enabled: true
          
eureka:
  client:
    service-url:
      defaultZone: http://mars-eureka:8761/eureka/

mqtt:
  client:
    id: mqtt.k3ms
  broker:
    url: tcp://10.2.26.112:1883
  username: techstore
  password: m751eLp
  
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"