server:
  port: 8080
   ssl:
    enabled: false
    key-store: file:/app/keystore.p12 
    key-store-password: pkcs1Mars2025
    key-store-type: PKCS12
    key-alias: localhostalias

spring:
  timezone: UTC+08:00
  application:
    name: MARS-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':  # Applies to all paths
            allowedOrigins: 
                - "http://localhost:3000"
            allowedMethods: 
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
            allowedHeaders: 
                - "*"
            allowCredentials: true
eureka:
  client:
    register-with-eureka: false
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
jwt:
  auth:
    secret: UUtvOYvp9YHz/kQpTYTimW52hefnIW5eh49gnJHZqp4=
    expiration: 300000 # Access token lifespan (5 min)

management:
  endpoints:
    web:
      exposure:
        include: "*"

socket-io:
  gateway: http://localhost:8101
  
soap:
  gateway: http://localhost:8999