server:
  port: 9806
  servlet:
    context-path: /api/v1/

spring:
  timezone: UTC+08:00
  application:
    name: mars-k3i

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
      
redis:
  address: redis://127.0.0.1:6379  # Redis server address with redis:// protocol
  password: chubb@RE@20
  database: 2                      # Default Redis database index

logging:
  config: "classpath:log4j2-dev.xml"